#!/bin/bash
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR/src/main/java"
BUILD_DIR="$SCRIPT_DIR/build"
CORE_PKG="com/ledger/core"
APP_PKG="com/ledger/app"

cd "$SCRIPT_DIR"

# On fresh clone, sources are generated by setup.sh (in parent dir); bootstrap with --build-only
if [[ ! -f "$SRC_DIR/$CORE_PKG/Account.java" ]]; then
  echo "Source files not found. Running ../setup.sh --build-only to generate and compile..."
  "$SCRIPT_DIR/../setup.sh" --build-only
  exit 0
fi

echo "Compiling Java sources..."
javac -d "$BUILD_DIR" \
  "$SRC_DIR/$CORE_PKG/Account.java" \
  "$SRC_DIR/$CORE_PKG/SynchronizedAccountService.java" \
  "$SRC_DIR/$APP_PKG/TransactionWorker.java" \
  "$SRC_DIR/$APP_PKG/LedgerApp.java"

echo "Build successful."
